// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaintTint.Infrastructure.Data;

#nullable disable

namespace PaintTint.Infrastructure.Migrations
{
    [DbContext(typeof(PaintTintDbContext))]
    partial class PaintTintDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PaintTint.Core.Entities.Base", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MaxTintPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PricePerLitre")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Bases");
                });

            modelBuilder.Entity("PaintTint.Core.Entities.Colorant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("CostPerMl")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Colorants");
                });

            modelBuilder.Entity("PaintTint.Core.Entities.DispenseJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseId")
                        .HasColumnType("int");

                    b.Property<decimal>("CanSizeLitres")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ShadeId")
                        .HasColumnType("int");

                    b.Property<decimal>("TintPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TotalColorantMl")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("BaseId");

                    b.HasIndex("ShadeId");

                    b.ToTable("DispenseJobs");
                });

            modelBuilder.Entity("PaintTint.Core.Entities.DispenseJobItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorantId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("DispenseJobId")
                        .HasColumnType("int");

                    b.Property<decimal>("DispensedMl")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ColorantId");

                    b.HasIndex("DispenseJobId");

                    b.ToTable("DispenseJobItems");
                });

            modelBuilder.Entity("PaintTint.Core.Entities.FormulaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseId")
                        .HasColumnType("int");

                    b.Property<int>("ColorantId")
                        .HasColumnType("int");

                    b.Property<decimal>("MlPerLitre")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("ShadeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaseId");

                    b.HasIndex("ColorantId");

                    b.HasIndex("ShadeId", "BaseId", "ColorantId")
                        .IsUnique();

                    b.ToTable("FormulaItems");
                });

            modelBuilder.Entity("PaintTint.Core.Entities.Shade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HexColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Shades");
                });

            modelBuilder.Entity("PaintTint.Core.Entities.DispenseJob", b =>
                {
                    b.HasOne("PaintTint.Core.Entities.Base", "Base")
                        .WithMany("DispenseJobs")
                        .HasForeignKey("BaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PaintTint.Core.Entities.Shade", "Shade")
                        .WithMany("DispenseJobs")
                        .HasForeignKey("ShadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Base");

                    b.Navigation("Shade");
                });

            modelBuilder.Entity("PaintTint.Core.Entities.DispenseJobItem", b =>
                {
                    b.HasOne("PaintTint.Core.Entities.Colorant", "Colorant")
                        .WithMany("DispenseJobItems")
                        .HasForeignKey("ColorantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PaintTint.Core.Entities.DispenseJob", "DispenseJob")
                        .WithMany("Items")
                        .HasForeignKey("DispenseJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colorant");

                    b.Navigation("DispenseJob");
                });

            modelBuilder.Entity("PaintTint.Core.Entities.FormulaItem", b =>
                {
                    b.HasOne("PaintTint.Core.Entities.Base", "Base")
                        .WithMany("FormulaItems")
                        .HasForeignKey("BaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PaintTint.Core.Entities.Colorant", "Colorant")
                        .WithMany("FormulaItems")
                        .HasForeignKey("ColorantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PaintTint.Core.Entities.Shade", "Shade")
                        .WithMany("FormulaItems")
                        .HasForeignKey("ShadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Base");

                    b.Navigation("Colorant");

                    b.Navigation("Shade");
                });

            modelBuilder.Entity("PaintTint.Core.Entities.Base", b =>
                {
                    b.Navigation("DispenseJobs");

                    b.Navigation("FormulaItems");
                });

            modelBuilder.Entity("PaintTint.Core.Entities.Colorant", b =>
                {
                    b.Navigation("DispenseJobItems");

                    b.Navigation("FormulaItems");
                });

            modelBuilder.Entity("PaintTint.Core.Entities.DispenseJob", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PaintTint.Core.Entities.Shade", b =>
                {
                    b.Navigation("DispenseJobs");

                    b.Navigation("FormulaItems");
                });
#pragma warning restore 612, 618
        }
    }
}
